app/blueprints/authentication/routes.py
from forms import LoginForm, SignUpForm
from app.models import User, db
from flask import Blueprint, render_template, redirect, url_for, flash
from flask import render_template, redirect, url_for, flash
from flask_login import login_user, logout_user

# imports for flask login 
from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods=["GET", "POST"])
def signup():
    # Create an instance of the SignUpForm
    form = SignUpForm()
    # Check if a POST request AND data is valid
    if form.validate_on_submit():
        print('Form Submitted and Validated!')
        # Get data from the form
        email = form.email.data
        username = form.username.data
        password = form.password.data
        print(email, username, password)
        # Query our user table to see if there are any users with either username or email from form
        check_user = User.query.filter( (User.username == username) | (User.email == email) ).all()
        # If the query comes back with any results
        if check_user:
            # Flash message saying that a user with email/username already exists
            flash('A user with that email and/or username already exists.', 'danger')
            return redirect(url_for('auth.signup'))
        # If check_user is empty, create a new record in the user table
        new_user = User(email=email, username=username, password=password)
        # Flash a success message
        flash(f'Thank you {new_user.username} for signing up!', 'success')
        # Redirect back to Home
        return redirect(url_for('site.index'))

    return render_template('sign_up.html', form=form)



@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # Get the username and password from the form
        username = form.username.data
        password = form.password.data
        print(username, password)
        # Query the user table to see if there is a user with that username
        user = User.query.filter_by(username=username).first()
        # Check if there is a user and that the password is correct
        if user is not None and user.check_password(password):
            # log the user in
            login_user(user)
            flash(f"{user.username} is now logged in", "warning")
            return redirect(url_for('site.index'))
        else:
            flash("Incorrect username and/or password", "danger")
            return redirect(url_for('auth.login'))
        
    return render_template('sign_in.html', form=form)

@auth.route('/logout', methods = ['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('site.index'))

app/blueprints/site/routes.py
from flask import Blueprint, render_template
from app.models import User, db, check_password_hash, Post
from flask import Blueprint, render_template, request, redirect, url_for, flash
from forms import LoginForm, PostForm

# imports for flask login 
from flask_login import login_user, logout_user, LoginManager, current_user, login_required


site = Blueprint('site', __name__, template_folder='site_templates')


@site.route('/', methods = ['GET', 'POST'])
def index():
    posts = Post.query.all()
    return render_template('index.html', posts=posts)

@site.route('/profile', methods = ['GET', 'POST'])
@login_required
def profile():
    form = PostForm()
    if form.validate_on_submit():
        # Get data from form
        brand = form.brand.data
        alcohol_level = form.alcohol_level.data
        class_alcohol = form.class_alcohol.data
        # Create new post instance which will also add to db
        new_post = Post(brand=brand, alcohol_level=alcohol_level, class_alcohol=class_alcohol, user_id=current_user.id)
        flash(f"{new_post.brand} has been created", "success")
        return redirect(url_for('site.index'))
        
    return render_template('create.html', form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <title>Prestige Alcohol | {% block title %} Hello {% endblock %}</title>
</head>
<body class="bg-secondary">
    
    {% include 'nav.html' %}

    <div class="container mt-5 p-3" style="height: 100%;">
        {% block content %}
        {% endblock %}
    </div>

    {% include 'footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/templates/footer.html
<footer class="footer" style="margin-top: 22%;">
    <div class="container-fluid py-4 py-md-5 px-4 px-md-3 text-body-secondary bg-dark" data-bs-theme="dark">
        <div class="row">
        <div class="col-lg-3 mb-3">
            <a class="d-inline-flex align-items-center mb-2 text-body-emphasis text-decoration-none" href="/" aria-label="Bootstrap">
                <div class="map_container">
                <div class="map-responsive">
                    <iframe src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA0s1a7phLN0iaD6-UE7m4qP-z21pH0eSc&amp;q=Eiffel+Tower+Paris+France" width="600" height="300" frameborder="0" style="border:0; width: 100%; height:100%" allowfullscreen=""></iframe>
                </div>
                </div>
            </a>
        </div>
        <div class="col-6 col-lg-2 offset-lg-1 mb-3">
            <h5>Info</h5>
            <ul class="list-unstyled">
            <li class="mb-2"><a href="/">Denver United States</a></li>
            <li class="mb-2"><a href="/">example@example.com</a></li>
            <li class="mb-2"><a href="/">Call Us: 706-555-4466</a></li>
            </ul>
        </div>
        <div class="col-6 col-lg-2 mb-3">
            <h5 id="Promotions">Promotions</h5>
            <ul class="list-unstyled">
            <li class="mb-2"><a href="/">Father's day Promotion</a></li>
            <li class="mb-2"><a href="/">Discount bonus</a></li>
            <li class="mb-2"><a href="/">Special Coupons</a></li>
            <li class="mb-2"><a href="/">Membership deals</a></li>
            </ul>
        </div>
        <div class="col-6 col-lg-2 mb-3">
            <h5>Social</h5>
            <ul class="list-unstyled">
            <li class="mb-2"><a href="/">facebook</a></li>
            <li class="mb-2"><a href="/">twitter</a></li>
            <li class="mb-2"><a href="/">Youtube</a></li>
            <li class="mb-2"><a href="/">Instagram</a></li>
            </ul>
        </div>
        </div>
    </div>
</footer>

app/templates/forms.html
{% block content %}
<form method="POST", action="">
    {{ form.csrf_token }}
    <div class="form-group">
        <fieldset id="brand-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = 'Please input email') }}
        </fieldset>
    </div>

        <fieldset id="model-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Please input password") }}
        </fieldset>

        <!-- Submit button area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}

</form>
{% endblock %}

app/templates/nav.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
  <div class="container">
        <a href="/" class="navbar-brand">Pretigious Drinks</a>
        <button 
            class="navbar-toggler" 
            type="button" 
            data-bs-toggle="collapse" 
            data-bs-target="#navmenu"
        ><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="/" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="#Promotions" class="nav-link">Promotions</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile') }}" class="nav-link">Collection</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
                    {% else %}
                    <li class="nav-item">
                        <a href="#Promotions" class="nav-link">Promotions</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.login') }}" class="nav-link">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup') }}" class="nav-link">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
        </div>
  </div>
</nav>